"""Export the interface contract as machine-readable JSON Schema.

The pydantic models in ``implicit_health_triage.schemas`` are the single source
of truth.  This script projects them into ``schemas/*.schema.json`` so that
neighbouring modules can validate payloads **without** importing this package —
useful when another skill is written in a different language or runs in a
different container.

Usage::

    python scripts/export_schemas.py            # write the files
    python scripts/export_schemas.py --check    # verify they are up to date

``tests/test_contract_schemas.py`` runs the ``--check`` path, so a model change
that is not re-exported fails the test suite instead of silently making the
committed schemas lie.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

from implicit_health_triage import schemas  # noqa: E402

SCHEMA_DIR = PROJECT_ROOT / "schemas"

#: (filename stem, model, role).  ``role`` is metadata for consumers, so it is
#: kept in ASCII to stay readable in any toolchain.
EXPORTS: tuple[tuple[str, type, str], ...] = (
    ("ConversationTurn", schemas.ConversationTurn, "input: from elderly-voice-duplex"),
    ("TriageRequest", schemas.TriageRequest, "input: HTTP POST /v1/triage"),
    ("TriageResponse", schemas.TriageResponse, "output: HTTP POST /v1/triage"),
    ("PartialIgnoredResponse", schemas.PartialIgnoredResponse, "output: HTTP is_final=false"),
    ("TriageResult", schemas.TriageResult, "output: core result"),
    ("HealthSignal", schemas.HealthSignal, "output: the three core fields"),
    ("HealthSignalRecord", schemas.HealthSignalRecord, "output: to family-digest-sync"),
)

_HEADER = "GENERATED by scripts/export_schemas.py — do not edit by hand."


def render(model: type, role: str) -> str:
    """Deterministic JSON text for one model."""

    schema = model.model_json_schema()
    schema = {"$schema": "https://json-schema.org/draft/2020-12/schema", **schema}
    schema["x-role"] = role
    schema["x-source"] = f"implicit_health_triage.schemas.{model.__name__}"
    schema["x-generated-by"] = _HEADER

    return json.dumps(schema, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def build() -> dict[Path, str]:
    return {SCHEMA_DIR / f"{stem}.schema.json": render(model, role) for stem, model, role in EXPORTS}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed schemas match the models instead of writing",
    )
    args = parser.parse_args()

    files = build()

    if args.check:
        stale = []
        for path, expected in files.items():
            if not path.exists():
                stale.append(f"missing: {path.name}")
            elif path.read_text(encoding="utf-8") != expected:
                stale.append(f"out of date: {path.name}")

        if stale:
            print("Interface schemas do NOT match the pydantic models:")
            for item in stale:
                print(f"  - {item}")
            print("\nRun:  python scripts/export_schemas.py")
            return 1

        print(f"Interface schemas up to date ({len(files)} files).")
        return 0

    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(PROJECT_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
