"""Fixed safety responses (task guide sections 16, 28).

The medication-safety wording is a constant, never generated by the chat model.
It has exactly three jobs::

    1. never give a concrete medication decision
    2. point back to the existing prescription / patient information leaflet
    3. defer to a doctor or pharmacist

Critically it must not answer "可以" / "不可以", must not name a number of
tablets, and must not suggest stopping or switching medication.
"""

from __future__ import annotations

#: Verbatim from task guide section 16.
MEDICATION_SAFETY_RESPONSE = (
    "这个涉及具体的用药剂量，我不能替您决定增加、减少或停止服药。"
    "请先按照医生给您的处方或药品说明来服用，"
    "如果不确定，最好联系医生或药师确认。"
)

#: Fallback when a health-care reply is unavailable or rejected (section 28, 48.5).
HEALTH_CARE_FALLBACK_RESPONSE = (
    "听起来您今天有些不舒服。您平时该吃的药都按原来的安排吃了吗？"
)

#: Deterministic output checker for the LLM-authored caring reply (section 28).
UNSAFE_OUTPUT_PATTERNS: tuple[str, ...] = (
    "多吃一颗",
    "多吃一片",
    "少吃一颗",
    "停药",
    "把药停了",
    "换成",
    "建议你吃",
    "你应该服用",
)


def unsafe_medical_output(text: str) -> bool:
    """True when a generated reply contains a forbidden medical instruction."""

    return any(pattern in (text or "") for pattern in UNSAFE_OUTPUT_PATTERNS)


def safe_health_care_response(text: str | None) -> str:
    """Return ``text`` when it is safe, otherwise the fixed fallback."""

    if not text or not text.strip() or unsafe_medical_output(text):
        return HEALTH_CARE_FALLBACK_RESPONSE

    return text.strip()


__all__ = [
    "HEALTH_CARE_FALLBACK_RESPONSE",
    "MEDICATION_SAFETY_RESPONSE",
    "UNSAFE_OUTPUT_PATTERNS",
    "safe_health_care_response",
    "unsafe_medical_output",
]
